// International Standard Lists for Occupations and Citizenships

export const CITIZENSHIPS = [
  'Afghan',
  'Albanian',
  'Algerian',
  'American',
  'Andorran',
  'Angolan',
  'Antiguan and Barbudan',
  'Argentine',
  'Armenian',
  'Australian',
  'Austrian',
  'Azerbaijani',
  'Bahamian',
  'Bahraini',
  'Bangladeshi',
  'Barbadian',
  'Belarusian',
  'Belgian',
  'Belizean',
  'Beninese',
  'Bhutanese',
  'Bolivian',
  'Bosnian and Herzegovinian',
  'Motswana (Botswana)',
  'Brazilian',
  'British',
  'Bruneian',
  'Bulgarian',
  'Burkinabe',
  'Burmese',
  'Burundian',
  'Cambodian',
  'Cameroonian',
  'Canadian',
  'Cape Verdean',
  'Central African',
  'Chadian',
  'Chilean',
  'Chinese',
  'Colombian',
  'Comorian',
  'Congolese',
  'Costa Rican',
  'Croatian',
  'Cuban',
  'Cypriot',
  'Czech',
  'Danish',
  'Djiboutian',
  'Dominican',
  'Dutch',
  'East Timorese',
  'Ecuadorian',
  'Egyptian',
  'Emirati',
  'English',
  'Equatorial Guinean',
  'Eritrean',
  'Estonian',
  'Ethiopian',
  'Fijian',
  'Filipino',
  'Finnish',
  'French',
  'Gabonese',
  'Gambian',
  'Georgian',
  'German',
  'Ghanaian',
  'Greek',
  'Grenadian',
  'Guatemalan',
  'Guinean',
  'Bissau-Guinean',
  'Guyanese',
  'Haitian',
  'Honduran',
  'Hungarian',
  'Icelander',
  'Indian',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Irish',
  'Israeli',
  'Italian',
  'Ivorian',
  'Jamaican',
  'Japanese',
  'Jordanian',
  'Kazakhstani',
  'Kenyan',
  'Kittitian and Nevisian',
  'Kuwaiti',
  'Kyrgyz',
  'Laotian',
  'Latvian',
  'Lebanese',
  'Mosotho (Lesotho)',
  'Liberian',
  'Libyan',
  'Liechtensteiner',
  'Lithuanian',
  'Luxembourgish',
  'Malagasy',
  'Malawian',
  'Malaysian',
  'Maldivian',
  'Malian',
  'Maltese',
  'Marshallese',
  'Mauritanian',
  'Mauritian',
  'Mexican',
  'Micronesian',
  'Moldovan',
  'Monacan',
  'Mongolian',
  'Montenegrin',
  'Moroccan',
  'Mozambican',
  'Namibian',
  'Nauruan',
  'Nepalese',
  'New Zealander',
  'Nicaraguan',
  'Nigerian',
  'Nigerien',
  'North Korean',
  'North Macedonian',
  'Norwegian',
  'Omani',
  'Pakistani',
  'Palauan',
  'Palestinian',
  'Panamanian',
  'Papua New Guinean',
  'Paraguayan',
  'Peruvian',
  'Polish',
  'Portuguese',
  'Qatari',
  'Romanian',
  'Russian',
  'Rwandan',
  'Saint Lucian',
  'Salvadoran',
  'Samoan',
  'Sammarinese',
  'Sao Tomean',
  'Saudi Arabian',
  'Scottish',
  'Senegalese',
  'Serbian',
  'Seychellois',
  'Sierra Leonean',
  'Singaporean',
  'Slovak',
  'Slovenian',
  'Solomon Islander',
  'Somali',
  'South African',
  'South Korean',
  'South Sudanese',
  'Spanish',
  'Sri Lankan',
  'Sudanese',
  'Surinamese',
  'Swazi',
  'Swedish',
  'Swiss',
  'Syrian',
  'Taiwanese',
  'Tajik',
  'Tanzanian',
  'Thai',
  'Togolese',
  'Tongan',
  'Trinidadian and Tobagonian',
  'Tunisian',
  'Turkish',
  'Turkmen',
  'Tuvaluan',
  'Ugandan',
  'Ukrainian',
  'Uruguayan',
  'Uzbek',
  'Ni-Vanuatu',
  'Venezuelan',
  'Vietnamese',
  'Welsh',
  'Yemeni',
  'Zambian',
  'Zimbabwean',
];

export const OCCUPATIONS = [
  'Accountant',
  'Actor',
  'Actress',
  'Administrator',
  'Advisor',
  'Aerospace Engineer',
  'Agricultural Worker',
  'Application Developer',
  'Architect',
  'Artist',
  'Auditor',
  'Aviation Specialist',
  'Backend Engineer',
  'Banker',
  'Biologist',
  'Business Analyst',
  'Business Development Executive',
  'Business Owner',
  'CEO',
  'CFO',
  'CTO',
  'Chef',
  'Chemist',
  'Civil Engineer',
  'Client Relations Specialist',
  'Construction Engineer',
  'Consultant',
  'Content Creator',
  'Cook',
  'Copywriter',
  'Counselor',
  'Culinary Specialist',
  'Customer Support Specialist',
  'Data Analyst',
  'Data Scientist',
  'Dental Professional',
  'Dentist',
  'Department Head',
  'Designer',
  'Director',
  'Doctor',
  'Driver',
  'Economist',
  'Educator',
  'Electrical Engineer',
  'Electronics Engineer',
  'Entrepreneur',
  'Event Manager',
  'Executive',
  'Farmer',
  'Financial Analyst',
  'Financial Researcher',
  'Fleet Operator',
  'Founder',
  'Frontend Engineer',
  'Graphic Designer',
  'Healthcare Specialist',
  'Hotel Professional',
  'Human Resources Manager',
  'Human Resources Specialist',
  'IT Consultant',
  'IT Specialist',
  'Illustrator',
  'Interpreter',
  'Investment Specialist',
  'Job Seeker',
  'Journalist',
  'Lawyer',
  'Lecturer',
  'Legal Counsel',
  'Linguist',
  'Logistics Manager',
  'Manager',
  'Mechanical Engineer',
  'Medical Staff',
  'Nurse',
  'Nursing Specialist',
  'Operations Manager',
  'Other',
  'Paralegal',
  'Performer',
  'Pharmaceutical Specialist',
  'Pharmacist',
  'Photographer',
  'Physician',
  'Pilot',
  'Postdoctoral Fellow',
  'Product Manager',
  'Product Owner',
  'Professor',
  'Project Manager',
  'Property Manager',
  'Psychologist',
  'Real Estate Agent',
  'Real Estate Broker',
  'Researcher',
  'Retired',
  'Sales Executive',
  'Sales Representative',
  'Scientist',
  'Scrum Master',
  'Software Engineer',
  'Strategy Specialist',
  'Student',
  'Supervisor',
  'Supply Chain Manager',
  'Surgeon',
  'Systems Administrator',
  'Teacher',
  'Tech Specialist',
  'Therapist',
  'Tourism Professional',
  'Translator',
  'UI UX Designer',
  'Unemployed',
  'Urban Planner',
  'Videographer',
  'Web Developer',
  'Writer',
];
