// International Standard Lists for Occupations and Citizenships

export const CITIZENSHIPS = [
  'Afghan',
  'Albanian',
  'Algerian',
  'American',
  'Andorran',
  'Angolan',
  'Antiguan / Barbudan',
  'Argentine',
  'Armenian',
  'Australian',
  'Austrian',
  'Azerbaijani',
  'Bahamian',
  'Bahraini',
  'Bangladeshi',
  'Barbadian',
  'Belarusian',
  'Belgian',
  'Belizean',
  'Beninese',
  'Bhutanese',
  'Bolivian',
  'Bosnian / Herzegovinian',
  'Motswana (Botswana)',
  'Brazilian',
  'British',
  'Bruneian',
  'Bulgarian',
  'Burkinabe',
  'Burmese / Myanma',
  'Burundian',
  'Cambodian',
  'Cameroonian',
  'Canadian',
  'Cape Verdean',
  'Central African',
  'Chadian',
  'Chilean',
  'Chinese',
  'Colombian',
  'Comorian',
  'Congolese',
  'Costa Rican',
  'Croatian',
  'Cuban',
  'Cypriot',
  'Czech',
  'Danish',
  'Djiboutian',
  'Dominican',
  'Dutch',
  'East Timorese',
  'Ecuadorian',
  'Egyptian',
  'Emirati',
  'English',
  'Equatorial Guinean',
  'Eritrean',
  'Estonian',
  'Ethiopian',
  'Fijian',
  'Filipino',
  'Finnish',
  'French',
  'Gabonese',
  'Gambian',
  'Georgian',
  'German',
  'Ghanaian',
  'Greek',
  'Grenadian',
  'Guatemalan',
  'Guinean',
  'Bissau-Guinean',
  'Guyanese',
  'Haitian',
  'Honduran',
  'Hungarian',
  'Icelander',
  'Indian',
  'Indonesian',
  'Iranian',
  'Iraqi',
  'Irish',
  'Israeli',
  'Italian',
  'Ivorian',
  'Jamaican',
  'Japanese',
  'Jordanian',
  'Kazakhstani',
  'Kenyan',
  'Kittitian / Nevisian',
  'Kuwaiti',
  'Kyrgyz',
  'Laotian',
  'Latvian',
  'Lebanese',
  'Mosotho (Lesotho)',
  'Liberian',
  'Libyan',
  'Liechtensteiner',
  'Lithuanian',
  'Luxembourgish',
  'Malagasy',
  'Malawian',
  'Malaysian',
  'Maldivian',
  'Malian',
  'Maltese',
  'Marshallese',
  'Mauritanian',
  'Mauritian',
  'Mexican',
  'Micronesian',
  'Moldovan',
  'Monacan',
  'Mongolian',
  'Montenegrin',
  'Moroccan',
  'Mozambican',
  'Namibian',
  'Nauruan',
  'Nepalese',
  'New Zealander',
  'Nicaraguan',
  'Nigerian',
  'Nigerien',
  'North Korean',
  'North Macedonian',
  'Norwegian',
  'Omani',
  'Pakistani',
  'Palauan',
  'Palestinian',
  'Panamanian',
  'Papua New Guinean',
  'Paraguayan',
  'Peruvian',
  'Polish',
  'Portuguese',
  'Qatari',
  'Romanian',
  'Russian',
  'Rwandan',
  'Saint Lucian',
  'Salvadoran',
  'Samoan',
  'Sammarinese',
  'Sao Tomean',
  'Saudi Arabian',
  'Scottish',
  'Senegalese',
  'Serbian',
  'Seychellois',
  'Sierra Leonean',
  'Singaporean',
  'Slovak',
  'Slovenian',
  'Solomon Islander',
  'Somali',
  'South African',
  'South Korean',
  'South Sudanese',
  'Spanish',
  'Sri Lankan',
  'Sudanese',
  'Surinamese',
  'Swazi',
  'Swedish',
  'Swiss',
  'Syrian',
  'Taiwanese',
  'Tajik',
  'Tanzanian',
  'Thai',
  'Togolese',
  'Tongan',
  'Trinidadian / Tobagonian',
  'Tunisian',
  'Turkish',
  'Turkmen',
  'Tuvaluan',
  'Ugandan',
  'Ukrainian',
  'Uruguayan',
  'Uzbek',
  'Ni-Vanuatu',
  'Venezuelan',
  'Vietnamese',
  'Welsh',
  'Yemeni',
  'Zambian',
  'Zimbabwean',
];

export const OCCUPATIONS = [
  'Accountant / Auditor',
  'Actor / Actress / Performer',
  'Architect / Urban Planner',
  'Artist / Designer / Illustrator',
  'Banker / Financial Analyst / Investment Specialist',
  'Biologist / Chemist / Scientist',
  'Business Analyst / Strategy Specialist',
  'Chef / Cook / Culinary Specialist',
  'Civil / Construction Engineer',
  'Consultant / Advisor',
  'Content Creator / Copywriter / Journalist',
  'Customer Support / Client Relations Specialist',
  'Data Scientist / Data Analyst',
  'Dentist / Dental Professional',
  'Doctor / Physician / Surgeon',
  'Driver / Logistics & Fleet Operator',
  'Economist / Financial Researcher',
  'Educator / Teacher / Lecturer / Professor',
  'Electrical / Electronics Engineer',
  'Entrepreneur / Business Owner / Founder',
  'Executive / C-Suite Officer (CEO, CTO, CFO, etc.)',
  'Graphic / UI/UX Designer',
  'Healthcare Specialist / Medical Staff',
  'Hospitality / Hotel & Tourism Professional',
  'Human Resources (HR) Manager / Specialist',
  'IT Specialist / Systems Administrator',
  'Lawyer / Legal Counsel / Paralegal',
  'Logistics & Supply Chain Manager',
  'Manager / Director / Department Head',
  'Mechanical / Aerospace Engineer',
  'Nurse / Nursing Specialist',
  'Operations Manager / Specialist',
  'Pharmacist / Pharmaceutical Specialist',
  'Photographer / Videographer',
  'Pilot / Aviation Specialist',
  'Product Manager / Product Owner',
  'Project Manager / Scrum Master',
  'Psychologist / Counselor / Therapist',
  'Real Estate Agent / Broker',
  'Researcher / Postdoctoral Fellow',
  'Retired',
  'Sales Representative / Business Development Executive',
  'Software Engineer / Application Developer',
  'Student (Undergraduate / Postgraduate / High School)',
  'Tech Specialist / IT Consultant',
  'Translator / Interpreter / Linguist',
  'Unemployed / Job Seeker / Between Roles',
  'Web Developer / Frontend / Backend Engineer',
  'Other / Unspecified',
];
